### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ioquatix** [rick/linode#39]
Some of the names seem a bit unusual for typical ruby:

e.g. 

`avail` vs `available`

`getlinodeid` vs `get_linode_id`

For people who English is not a native language, this can be hard to read/understand.

**Comment by ioquatix** [comment]
Keep in mind that `avail` is actually a word in its own right, with an entirely different meaning to `available`.

**Comment by displague** [comment]
That's a fair point.  `avail` follows the naming provided by the API.  This wrapper tries to [match the upstream](https://www.linode.com/api/utility/avail.distributions).

I couldn't find any references to getlinodeid, but I agree, you will find things like `getapikey` and once again this is taken from the [upstream API](https://www.linode.com/api/account/user.getapikey).

While the documentation in this project could be improved, the convention set early on was to mimic the upstream naming.  The Linode API docs may help in translation because it offers the parameter names and and their description.

**Comment by ioquatix** [comment]
Yeah, I thought that might be the case. Thanks so much for your time responding to this issue and for your work on this gem.
